package ecommerce.modules.cart.exception;

public enum CartErrorCode {
    CART_NOT_FOUND,
    ITEM_NOT_FOUND,
    PRODUCT_NOT_FOUND,
    VARIANT_NOT_FOUND,
    QUANTITY_EXCEEDED,
    ITEM_UNAVAILABLE,
    CART_EXPIRED,
    CART_ALREADY_CHECKED_OUT,
    COUPON_NOT_FOUND,
    COUPON_INACTIVE,
    COUPON_EXPIRED,
    COUPON_USAGE_LIMIT_REACHED,
    COUPON_MIN_AMOUNT_NOT_MET,
    PRICE_RESOLUTION_FAILED,
    GUEST_CART_NOT_FOUND,
    MERGE_FAILED
}
