package ecommerce.modules.refund.enums;

public enum ReturnAuditAction {
    CREATED,
    REVIEW_STARTED,
    APPROVED,
    REJECTED,
    CANCELLED,
    ESCALATED,
    SHIPMENT_INITIATED,
    IN_TRANSIT,
    RECEIVED,
    INSPECTION_STARTED,
    INSPECTION_COMPLETED,
    DISPOSITION_RECORDED,
    EVIDENCE_ADDED,
    NOTE_ADDED,
    STATUS_CHANGED
}
